### ISSUE TITLE
per-interpreter: pending calls (from ceval state)

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#24]
(Note: this was reverted, so the underlying problem needs to be addressed and then the PR re-merged.)

Move `PyRuntimeState.ceval.pending` to `PyInterpreterState.ceval.pending`.

- [x] move pending calls from `PyRuntimeState` to `PyInterpreterState`
- [x] move eval "breaker" flag to `PyInterpreterState`
- [x] pass `PyInterpreterState *` to related macros (rather than rely on `PyThreadState_Get()`)
- [x] sort out what "main" thread means, when per-interpreter
- [x] fix usage of `Py_AddPendingCall()`

**Comment by ericsnowcurrently** [comment]
https://bugs.python.org/issue35423
https://github.com/python/cpython/pull/10972

https://bugs.python.org/issue33608
https://github.com/python/cpython/pull/9334

**Comment by phmc** [comment]
Just pinging here too: I've added some thoughts on the crash exposed by the pending calls changes on the bpo issue https://bugs.python.org/issue33608

**Comment by ericsnowcurrently** [comment]
Thanks!  I'll take a look and respond over there.  (Hopefully I can get to it today.)

**Comment by ericsnowcurrently** [comment]
FTR, this is effectively blocked by https://bugs.python.org/issue36476, "Runtime finalization assumes all other threads have exited."

**Comment by vstinner** [comment]
> move eval "breaker" flag to PyInterpreterState

and

>  fix usage of Py_AddPendingCall()

Are fixed by https://github.com/python/cpython/commit/50e6e991781db761c496561a995541ca8d83ff87 : see https://bugs.python.org/issue39984

**Comment by vstinner** [comment]
> Move PyRuntimeState.ceval.pending to PyInterpreterState.ceval.pending.

is done, so I close the issue.

**Comment by ericsnowcurrently** [comment]
Thanks @vstinner!  I'm glad that at least this part of https://bugs.python.org/issue33608 has made it in. :smile:
