### ISSUE TITLE
per-interpreter: gc

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#29]
Move `PyRuntimeState.gc` to `PyInterpreterState.gc`.

Notable concerns:
* can be moved separately from rest of mem state?
* do we still need a global state for anything?  (just use "main"?)

(https://bugs.python.org/issue36854)

**Comment by vstinner** [comment]
I closed https://bugs.python.org/issue36854 so this issue can be closed as well, no?

**Comment by ericsnowcurrently** [comment]
oh, funny, I moved it to "done" but that didn't close it :)
