### ISSUE TITLE
per-interpreter: tracing flag (from ceval)

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#32]
* copy `PyRuntimeState.ceval.tracing_possible` to `PyInterpreterState.ceval.tracing_possible`
* leave the global flag in place

**Comment by LewisGaul** [comment]
Hey, here as a first-time contributor. I've had a look into this and found the relevant `struct pyruntimestate`, `_ceval_runtime_state.tracing_possible` and `struct _is` in `pycore_pystate.h`. It seems the interpreter state doesn't have a `ceval` field - what is the change that's actually needed here?

**Comment by ericsnowcurrently** [comment]
`PyInterpreterState` (AKA `struct _is`) will need a `ceval` field similar to how it currently exists on `_PyRuntimeState` (AKA `struct pyruntimestate`).  We also need to make sure none of the current semantics get lost in the shuffle.

FWIW, the question of leaving the global flag in place is still debatable.

**Comment by LewisGaul** [comment]
I've created a new interpreter state ceval struct with just the `tracing_possible` flag. Should it contain any of the other fields from the runtime state ceval struct? I also have a question about how to set the value of the new flag, see the attached diff.

[subinterp-tracing-flag.txt](https://github.com/ericsnowcurrently/multi-core-python/files/3804090/subinterp-tracing-flag.txt)

P.S. Is attaching a diff as above the preferred way to discuss code changes, or would it be easier to use a PR open in my own cpython repo?

**Comment by vstinner** [comment]
Done by https://github.com/python/cpython/commit/dab8423d220243efabbbcafafc12d90145539b50 in https://bugs.python.org/issue39984

**Comment by ericsnowcurrently** [comment]
Thanks, @vstinner!
