### ISSUE TITLE
GC tied to main interpreter

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#36]
https://bugs.python.org/issue24554

GC should happen when a subinterpreter is destroyed (GC currently tied to main interpreter context)

See also:
https://github.com/GrahamDumpleton/mod_wsgi/issues/43
http://emptysqua.re/blog/a-normal-accident-in-python-and-mod-wsgi/

**Comment by vstinner** [comment]
I fixed https://bugs.python.org/issue36854 and https://bugs.python.org/issue24554

**Comment by ericsnowcurrently** [comment]
Thanks @vstinner!
