### ISSUE TITLE
Crash with subinterpreters and Py_NewInterpreter()

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#56]
https://bugs.python.org/issue30060

**Comment by jakirkham** [comment]
This appears to be a Python 2.7 issue only, right?

**Comment by ericsnowcurrently** [comment]
Hmm, if it is 2.7-only then there's nothing to do. :)  It would be worth double-checking.  Given how much the runtime initialization/finalization implementation has changed since 2.7, I wouldn't be surprised if it was no longer a problem.

**Comment by ericsnowcurrently** [comment]
Good catch, BTW.

**Comment by jakirkham** [comment]
Sure. Happy to help.

It's probably worth noting they were building Python 2.7 with VS 2015, which is not officially supported AFAIK. Additionally they were patching it.

So this may be far enough off the beaten path such that it isn't worth worrying about. Happy to defer to your judgement though.

**Comment by ericsnowcurrently** [comment]
Yeah, let's not worry about it unless there is a more clearly relevant report. :)
