### ISSUE TITLE
FIX a memory leak

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#58]
https://bugs.python.org/issue31200
https://github.com/python/cpython/pull/13168

**Comment by vstinner** [comment]
https://bugs.python.org/issue31200 was closed.  I added _PyUnicode_FiniEncodings() in commit https://github.com/python/cpython/commit/bf305cc6f05948f264349a6a6c6fd7d49c1839d3. It's called indirectly by Py_EndInterpreter(): finalize_interp_types() calls _PyUnicode_Fini(). I close this issue.
