### ISSUE TITLE
Question: How is the project coming along?And How do We join it?

### ISSUE THREAD

**Issue by Rocky5241** [ericsnowcurrently/multi-core-python#60]
Hi Eric Snow,

We currently use Python for some data processing on mobile devices. Due to performance requirements, we have made a lot of changes to Python 2.7 to support multiple Interpreters concurrent execution (using TLS, and tailoring some libraries we don't need). At the same time we plan to upgrade Python to the latest 3.9.

Recently we saw PEP554 and found that our previous technical solution is very similar to your idea. So I am wondering how the community is currently progressing in PEP554? I'm not sure if the results of our previous work are valuable to the community. How do we join it?

A few days ago I tried to contact you through ericsnowcurrently@gmail.com, but unsuccessfully. So try to get in touch with you through the issue.

Regards,

Rocky Li

**Comment by ericsnowcurrently** [comment]
I've responded by email.  (sorry for the long delay)
