### ISSUE TITLE
Language Summit talk (PyCon 2020)

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#62]
By April the initial phase of the project should be wrapping up.  This would be a good time to provide a retrospective.  I've submitted a proposal for such a presentation.  Any collaborators here that will be at the language summit are welcome to co-present.

I'd like to cover the following high-level topics:

1. the problems we're solving (multi-core; concurrency model)
2. the approach we took (subinterpreters: PEP 554, "stop sharing the GIL")
3. the general technical challenges
   + existing bugs and rough corners in the runtime (esp. init & fini & with subinterpreters)
   + eliminating process-global state in the runtime
   + guarding against other unsafe cross-interpreter interactions
   + extension modules (subinterpreter compatibility)
4. some specific technical challenges and their solutions (limited by the time slot; maybe spill out into extra talk proposals)
5. who helped, why, and how collaboration worked out
6. what's next?

Here are more specific technical challenges/solutions (i.e. item 4) that would be worth covering either here or in extra talks:

* runtime init [PEP 432, etc.]
* leaking internals into public C-API [Include/internal]
* runtime fini
* unsafe global runtime state
   - components: GC, pending calls, allocators, etc.
   - singletons: None, small ints, etc.
   - free lists & caches
   - _Py_IDENTIFIER()
   - static types
   - ...
   - making sure we don't accidentally add more [tooling]
* stdlib module (PEP 554)
   - inter-interpreter communication [channels]
   - thread safety for cross-interpreter interaction (e.g. in channels)
   - copy inefficiencies in channels [no-copy via buffer protocol, etc.]
   - channel_send_wait() (notify-on-recv)
   - propagating exceptions
* global state in extension modules [PEPs, coordination w/ major extensions, etc.]

My proposal:

```
The project (see https://github.com/ericsnowcurrently/multi-core-python) has been the main focus of my CPython contributions since around 2015.  It's reasonable to plan on the initial/core phase of the project to be wrapping up at PyCon, so this is a perfect time to offer a retrospective.

Those at the language summit will learn about:

* what we did (generally)
* the value it adds to the core team
* the value it adds to the community
* what changed
* what potential problems we introduced (and possible resolutions)
* what happened to the GIL
* implications on CPython performance
* impact on other Python implementations
* tricky parts of the low-level CPython runtime to be aware of
* where we moved things and why
* non-novel technical solutions to challenges we faced
   + helps attendees identify new problems due to those solutions
   + helps attendees working on related components
* what's left to be done
* (interesting) opportunities for improvements
* what would have made this project easier (and we should consider doing still)

(See https://github.com/ericsnowcurrently/multi-core-python/issues/62 for more details.) 
(I've invited other core collaborators to co-present.)
```

**Comment by nanjekyejoannah** [comment]
@ericsnowcurrently when should I look at having a PR for high-level sub-interpreters for review atleast upstream is April too early. IIRC, the PEP is not decided yet.

**Comment by ericsnowcurrently** [comment]
We'll ping Antoine in the next month or so.  I don't expect much more than one round of feedback at this point, given that we've done 3 already and the last one didn't get much response. :smile:  So April seems reasonable to me (assuming the PEP is accepted, which I anticipate to be true).

**Comment by nanjekyejoannah** [comment]
I am not likely to come for Pycon this year but I will communicate status to you and will ensure I open a PR for review upstream i.e CPython repo before March for the high-level part of sub-interpreters as I look like I may have time this Feb.

**Comment by vstinner** [comment]
> Any collaborators here that will be at the language summit are welcome to co-present.

I don't know if it's worth it that I co-present, but I can share that I did for subinterpreters over the last months on better isolating subinterpreters:

* Passing explicitely tstate: https://vstinner.github.io/cpython-pass-tstate.html
* Move GC state into PyInterpreterState
* Making small integer singletons per interpreter

Right now I'm working on https://bugs.python.org/issue39511 which is not done yet.

**Comment by encukou** [comment]
Happy to co-present. Time is short, but I believe I can fit the highlights from my side into a minute.
* Progress on [PEP 573 -- Module State Access](https://www.python.org/dev/peps/pep-0573/) was side-tracked by [PEP 590 -- Vectorcall](https://www.python.org/dev/peps/pep-0590/) (whose early iterations promised to help with PEP 573 much more than it did in the end), but at PyCon there will hopefully be something to present.
* Stdlib extension modules are being ported (by external contributors!); pain points and omissions are being identified.

I'll revisit this closer to the deadline; maybe I could take some of the topics from this issue and fill a separate talk+discussion slot.

**Comment by ericsnowcurrently** [comment]
@vstinner, sounds good.  At the very least I'll make sure the slides cover the various work that everyone has been doing. :smile:

@encukou, yeah, we can work it out either way.  Regardless, I figured if anyone had enough to talk about then then could get a dedicated slot (or do a lightning talk).

**Comment by ericsnowcurrently** [comment]
This ended up being a lightning talk. :smile:  Here are the slides:

https://docs.google.com/presentation/d/16M3v1sEOJO0xoMW9qupAzyPsYLfseeWv9zXXAMee4aE
